- alpha: 0.2929491083277872
  blur_kernel_size: 39
  glitch_size: 57
  hue_shift: 124
  num_glitches: 21
  sat_shift: 96
  timestamp: 04-21-2025 23-01
  val_hue_shift: 81
  val_shift: 11
  val_threshold: 234
  x_size: 0
  x_speed: 0
  y_size: 0
  y_speed: 0
- alpha: 0.10906409002310913
  blur_kernel_size: 67
  glitch_size: 75
  hue_shift: 50
  num_glitches: 61
  sat_shift: 96
  timestamp: 04-21-2025 23-01
  val_hue_shift: 120
  val_shift: 242
  val_threshold: 186
  x_size: 0
  x_speed: 0
  y_size: 0
  y_speed: 0
- alpha: 0.3972870650693181
  blur_kernel_size: 21
  glitch_size: 37
  hue_shift: 76
  num_glitches: 93
  sat_shift: 33
  timestamp: 04-21-2025 23-17
  val_hue_shift: 25
  val_shift: 253
  val_threshold: 63
  x_shift: 149
  y_shift: -50
- alpha: 0.9632010070017307
  blur_kernel_size: 5
  glitch_size: 7
  hue_shift: 180
  num_glitches: 47
  sat_shift: 253
  timestamp: 04-19-2025 13-31
  val_hue_shift: -97
  val_shift: 47
  val_threshold: 103
  x_size: 32
  x_speed: -0.12785264674196162
  y_size: 24
  y_speed: 0.801586755515793
- alpha: 0.17791426387854326
  blur_kernel_size: 25
  glitch_size: 180
  hue_shift: 216
  num_glitches: 17
  sat_shift: 51
  timestamp: 04-19-2025 13-31
  val_hue_shift: -148
  val_shift: 32
  val_threshold: 91
  x_size: 0
  x_speed: 0.4743872998965515
  y_size: 85
  y_speed: 0.4615221775106495
- alpha: 0.95
  blur_kernel_size: 1
  glitch_size: 1
  hue_shift: 100
  num_glitches: 0
  sat_shift: 100
  timestamp: 04-19-2025 13-33
  val_hue_shift: 0
  val_shift: 50
  val_threshold: 0
  x_size: 0
  x_speed: 0
  y_size: 0
  y_speed: 0
- alpha: 0.28989293640576697
  blur_kernel_size: 29
  glitch_size: 13
  hue_shift: 37
  num_glitches: 40
  sat_shift: 214
  timestamp: 04-19-2025 13-43
  val_hue_shift: 74
  val_shift: 113
  val_threshold: 247
  x_size: 73
  x_speed: 0.7768955528647858
  y_size: 18
  y_speed: 0.3610791993970215
- alpha: 0.1142751417372857
  blur_kernel_size: 3
  glitch_size: 24
  hue_shift: 58
  num_glitches: 75
  sat_shift: 135
  timestamp: 04-19-2025 14-11
  val_hue_shift: -62
  val_shift: 181
  val_threshold: 110
  x_size: 0
  x_speed: 0.30340457426261724
  y_size: 43
  y_speed: -0.9885872904144624
- alpha: 0.1142751417372857
  blur_kernel_size: 3
  glitch_size: 24
  hue_shift: 58
  num_glitches: 75
  sat_shift: 135
  timestamp: 04-19-2025 14-14
  val_hue_shift: -62
  val_shift: 181
  val_threshold: 110
  x_size: 0
  x_speed: 0.30340457426261724
  y_size: 43
  y_speed: -0.9885872904144624
- alpha: 0.4230000078678131
  blur_kernel_size: 1
  glitch_size: 10
  hue_shift: 14
  num_glitches: 12
  sat_shift: 44
  timestamp: 04-20-2025 21-45
  val_hue_shift: 60
  val_shift: 188
  val_threshold: 118
  x_size: 0
  x_speed: 0
  y_size: 0
  y_speed: 0
- alpha: 0.1923694422846265
  blur_kernel_size: 47
  glitch_size: 95
  hue_shift: 1
  num_glitches: 71
  sat_shift: 172
  timestamp: 04-21-2025 22-59
  val_hue_shift: 175
  val_shift: 0
  val_threshold: 29
  x_size: 0
  x_speed: 0
  y_size: 0
  y_speed: 0
- alpha: 0.375
  blur_kernel_size: 1
  glitch_size: 22
  hue_shift: 153
  num_glitches: 62
  sat_shift: 168
  timestamp: 04-21-2025 23-43
  val_hue_shift: 177
  val_shift: 170
  val_threshold: 158
  x_shift: -196
  y_shift: -240
- alpha: 0.5870000123977661
  blur_kernel_size: 1
  glitch_size: 24
  hue_shift: 58
  num_glitches: 0
  sat_shift: 137
  timestamp: 04-22-2025 15-13
  val_hue_shift: 0
  val_shift: 51
  val_threshold: 110
  x_shift: 320
  y_shift: -4
- alpha: 0.5870000123977661
  blur_kernel_size: 1
  glitch_size: 24
  hue_shift: 58
  num_glitches: 0
  sat_shift: 137
  timestamp: 04-22-2025 15-13
  val_hue_shift: 0
  val_shift: 51
  val_threshold: 110
  x_shift: 320
  y_shift: -4
- alpha: 0.18249017317291372
  blur_kernel_size: 9
  glitch_size: 63
  hue_shift: 76
  num_glitches: 0
  sat_shift: 191
  timestamp: 04-22-2025 15-16
  val_hue_shift: 157
  val_shift: 100
  val_threshold: 255
  x_shift: -564
  y_shift: 342
- plasma_speed: 1.0
  plasma_distance: 1.0
  plasma_color_speed: 1.0
  plasma_flow_speed: 1.0
  plasma_speed_frequency: 0.5
  plasma_speed_amplitude: 1.0
  plasma_speed_phase: 0.0
  plasma_speed_seed: 0
  plasma_speed_shape: 1
  plasma_speed_noise_octaves: 6
  plasma_speed_noise_persistence: 0.5
  plasma_speed_noise_lacunarity: 2.0
  plasma_speed_noise_repeat: 100
  plasma_speed_noise_base: 456
  plasma_distance_frequency: 0.5
  plasma_distance_amplitude: 1.0
  plasma_distance_phase: 0.0
  plasma_distance_seed: 0
  plasma_distance_shape: 1
  plasma_distance_noise_octaves: 6
  plasma_distance_noise_persistence: 0.5
  plasma_distance_noise_lacunarity: 2.0
  plasma_distance_noise_repeat: 100
  plasma_distance_noise_base: 456
  plasma_color_speed_frequency: 0.5
  plasma_color_speed_amplitude: 1.0
  plasma_color_speed_phase: 0.0
  plasma_color_speed_seed: 0
  plasma_color_speed_shape: 1
  plasma_color_speed_noise_octaves: 6
  plasma_color_speed_noise_persistence: 0.5
  plasma_color_speed_noise_lacunarity: 2.0
  plasma_color_speed_noise_repeat: 100
  plasma_color_speed_noise_base: 456
  plasma_flow_speed_frequency: 0.5
  plasma_flow_speed_amplitude: 1.0
  plasma_flow_speed_phase: 0.0
  plasma_flow_speed_seed: 0
  plasma_flow_speed_shape: 1
  plasma_flow_speed_noise_octaves: 6
  plasma_flow_speed_noise_persistence: 0.5
  plasma_flow_speed_noise_lacunarity: 2.0
  plasma_flow_speed_noise_repeat: 100
  plasma_flow_speed_noise_base: 456
  osc0_frequency: 0.5
  osc0_amplitude: 1.0
  osc0_phase: 0.0
  osc0_seed: 0
  osc0_shape: 0
  osc0_noise_octaves: 6
  osc0_noise_persistence: 0.5
  osc0_noise_lacunarity: 2.0
  osc0_noise_repeat: 100
  osc0_noise_base: 456
  osc1_frequency: 0.5
  osc1_amplitude: 1.0
  osc1_phase: 0.0
  osc1_seed: 0
  osc1_shape: 1
  osc1_noise_octaves: 6
  osc1_noise_persistence: 0.5
  osc1_noise_lacunarity: 2.0
  osc1_noise_repeat: 100
  osc1_noise_base: 456
  osc2_frequency: 0.5
  osc2_amplitude: 1.0
  osc2_phase: 0.0
  osc2_seed: 0
  osc2_shape: 2
  osc2_noise_octaves: 6
  osc2_noise_persistence: 0.5
  osc2_noise_lacunarity: 2.0
  osc2_noise_repeat: 100
  osc2_noise_base: 456
  osc3_frequency: 0.5
  osc3_amplitude: 1.0
  osc3_phase: 0.0
  osc3_seed: 0
  osc3_shape: 3
  osc3_noise_octaves: 6
  osc3_noise_persistence: 0.5
  osc3_noise_lacunarity: 2.0
  osc3_noise_repeat: 100
  osc3_noise_base: 456
  frame_skip: 1
  alpha: 0.0
  temporal_filter: 1.0
  sequence: 0
  x_shift: 0
  y_shift: 0
  zoom: 1.0
  r_shift: 0.0
  polar_x: 0
  polar_y: 0
  polar_radius: 1.0
  lissajous_A: 50
  lissajous_B: 50
  lissajous_a: 50
  lissajous_b: 50
  lissajous_delta: 0
  hue_shift: 0
  sat_shift: 0
  val_shift: 0
  posterize_levels: 2.0
  solarize_threshold: 0.0
  num_hues: 8
  val_threshold: 0
  val_hue_shift: 0
  hue_invert_angle: 0
  hue_invert_strength: 0.0
  contrast: 1.0
  brightness: 0
  sharpen_type: 0
  sharpen_intensity: 4.0
  blur_type: 1
  blur_kernel_size: 1
  num_glitches: 0
  glitch_size: 1
  noise_type: 0
  noise_intensity: 0.1
  shape_x_shift: 0
  shape_y_shift: 0
  shape_type: 0
  line_hue: 0
  line_sat: 255
  line_val: 255
  line_weight: 2
  line_opacity: 0.66
  size_multiplier: 0.9
  aspect_ratio: 1.0
  rotation_angle: 0
  multiply_grid_x: 2
  multiply_grid_y: 2
  grid_pitch_x: 100
  grid_pitch_y: 100
  fill_hue: 120
  fill_sat: 100
  fill_val: 255
  fill_opacity: 0.25
  canvas_rotation: 0
  pattern_type: 0
  pattern_speed: 1.0
  pattern_use_fractal: 0
  pattern_octaves: 4
  pattern_gain: 0.2
  pattern_lacunarity: 2.0
  bar_x_freq: 0.1
  bar_y_freq: 0.1
  bar_x_offset: 2.0
  bar_y_offset: 1.0
  pattern_mod: 1.0
  pattern_r: 127
  pattern_g: 127
  pattern_b: 127
  pattern_grid_size: 30
  pattern_color_shift: 127
  pattern_color_blend: 127
  pattern_distance: 5.0
  pattern_wave_freq_x: 0.05
  pattern_wave_freq_y: 0.05
  pattern_brightness: 50.0
  pattern_radial_freq: 30
  pattern_angular_freq: 1
  pattern_radial_mod: 1.0
  pattern_angle_mod: 1.0
  x_hue: 0.5
  y_hue: 0.5
  pperlin_scale_x: 0.005
  pperlin_scale_y: 0.005
  pperlin_octaves: 6
  pperlin_persistence: 0.5
  pperlin_lacunarity: 2.0
  pperlin_time_speed: 0.1
  pfractal_amplitude: 1.5
  pfractal_octaves: 4
  x_perturb: 25.0
  y_perturb: 25.0
  phase_speed: 1.0
  posc0_val: 1.15
  posc1_val: 1.1
  posc2_val: 1.1
  posc0_frequency: 0.5
  posc0_amplitude: 1.0
  posc0_phase: 0.0
  posc0_seed: 0
  posc0_shape: 0
  posc0_noise_octaves: 6
  posc0_noise_persistence: 0.5
  posc0_noise_lacunarity: 2.0
  posc0_noise_repeat: 100
  posc0_noise_base: 456
  posc1_frequency: 0.5
  posc1_amplitude: 1.0
  posc1_phase: 0.0
  posc1_seed: 0
  posc1_shape: 0
  posc1_noise_octaves: 6
  posc1_noise_persistence: 0.5
  posc1_noise_lacunarity: 2.0
  posc1_noise_repeat: 100
  posc1_noise_base: 456
  posc2_frequency: 0.5
  posc2_amplitude: 1.0
  posc2_phase: 0.0
  posc2_seed: 0
  posc2_shape: 0
  posc2_noise_octaves: 6
  posc2_noise_persistence: 0.5
  posc2_noise_lacunarity: 2.0
  posc2_noise_repeat: 100
  posc2_noise_base: 456
  posc3_frequency: 0.5
  posc3_amplitude: 1.0
  posc3_phase: 0.0
  posc3_seed: 0
  posc3_shape: 0
  posc3_noise_octaves: 6
  posc3_noise_persistence: 0.5
  posc3_noise_lacunarity: 2.0
  posc3_noise_repeat: 100
  posc3_noise_base: 456
  key_upper_hue: 0
  key_lower_hue: 0
  key_upper_sat: 255
  key_lower_sat: 0
  key_upper_val: 255
  key_lower_val: 0
  reflection_mode: 0
  num_metaballs: 5
  min_radius: 40
  max_radius: 80
  radius_multiplier: 1.0
  max_speed: 3
  speed_multiplier: 1.0
  threshold: 1.6
  smooth_coloring_max_field: 1.5
  metaball_skew_angle: 0.0
  metaball_skew_intensity: 0.0
  metaball_zoom: 1.0
  metaball_hue: 0.0
  metaball_saturation: 255.0
  metaball_value: 255.0
  metaballs_feedback: 0.95
  metaballs_frame_blend: 0.5
  x_sync_freq: 1.0
  x_sync_amp: 0.0
  x_sync_speed: 9.0
  y_sync_freq: 1.0
  y_sync_amp: 0.0
  y_sync_speed: 9.0
  warp_type: 0
  warp_angle_amt: 30
  warp_radius_amt: 30
  warp_speed: 10
  warp_use_fractal: 0
  warp_octaves: 4
  warp_gain: 0.5
  warp_lacunarity: 2.0
  x_speed: 1.0
  x_size: 20.0
  y_speed: 1.0
  y_size: 10.0
